### ISSUE TITLE
error message after installing plugin

### ISSUE THREAD

**Issue by hboetes** [theforeman/foreman_monitoring#13]
After install the monitoring plugin I get this error message while visiting the foreman/hosts page:
```
Oops, we're sorry but something went wrong ERROR: relation "monitoring_results" does not exist LINE 5: WHERE a.attrelid = '"monitoring_results"'::re... ^ 
```

**Comment by timogoebel** [comment]
@hboetes : Have you run `foreman-rake db:migrate` and `foreman-rake db:seed`? This should fix your issues. If not, could you give me the whole stacktrace from /var/log/foreman/production.log?

**Comment by hboetes** [comment]
@timogoebel : Yes that fixed the problem.
Do you realise this isn't documented anywhere? Could you please document all those steps? This is taking me a lot of time.

**Comment by dgoetz** [comment]
I addressed this and the mentioned service restart from theforeman/smart_proxy_monitoring#4 in the commit. Any further suggestions?
