### ISSUE TITLE
acknowledged problem stick

### ISSUE THREAD

**Issue by hboetes** [theforeman/foreman_monitoring#17]
After icinga noticed a problem and me acknowledging it the problem remains
![selection_002](https://user-images.githubusercontent.com/2285225/27593437-7d29df7e-5b57-11e7-9271-d09c7e1e7c6b.png)
Although they have long gone from the icinga notifications. The unacknowledged problems do disappear.

**Comment by dgoetz** [comment]
@timogoebel: I found the typo which caused the bug and uploaded the fix to the smart proxy plugin, but now it only removes the acknowledgement or changes the state. I think it is a timing issue as both events happen at the same time and the foreman plugin skips events if the timestamp is not newer.

**Comment by timogoebel** [comment]
@dgoetz: Yes, that could work. I even think, we should change this anyways.

I'm wondering, why this line was necessary in the firstplace. Could that also lead to the timing problem?

https://github.com/theforeman/smart_proxy_monitoring/blob/d30d5e6c34e491a063c1d46a433da24cdf034fb2/lib/smart_proxy_monitoring_icinga2/icinga2_result_uploader.rb#L27

**Comment by timogoebel** [comment]
Actually, that doesn‘t quite solve this for me. I wrote a couple of unit tests to reproduce the bug. Will open a PR for discussion soon.

**Comment by timogoebel** [comment]
#37 should contain a fix for this.

**Comment by hboetes** [comment]
I just upgraded the plugin and the patch is not yet in stable, or am I missing something?

root@foreman01 ~ # updatedb
root@foreman01 ~ # grep 'updates\[:timestamp\].to_time' $(locate app/models/monitoring_result.rb)
root@foreman01 ~ #

**Comment by timogoebel** [comment]
@hboetes: The `0.1-stable` branch contains commit 974e82325e44c23a5e7e53eef20617c6888998c8. I haven't made a new release, yet.

**Comment by hboetes** [comment]
Ah, I had to replace the 0.1.1 tag with 0.1.2
