### ISSUE TITLE
Conflicts with other plugins that also alias_method_chain

### ISSUE THREAD

**Issue by GregSutcliffe** [theforeman/foreman_monitoring#30]
Hey guys,

in the last few days I've had two users report issues with `monitoring` due to it's extension of `host_title_actions` (and possibly other methods). Both `foreman_cockpit` and `foreman_salt` have conflicted with `monitoring` - see http://projects.theforeman.org/issues/21523 for an example.

My knowledge of alias_method_chain is rusty, but IIRC there's a way to set it up to play nice with other plugins - maybe @tbrisker might have thoughts?

**Comment by timogoebel** [comment]
@GregSutcliffe: Thanks for letting us know. f596308d778fa15ddc4f886e467da036a32bd5df already replaces `alias_method_chain` with `Module.prepend`.
I'll cut a new release that included this fix as soon as possible. However, today is a public holiday in Germany so it might take a few more days.

**Comment by timogoebel** [comment]
I believe, the only way to fix this is if all plugins would drop the use of `alias_method_chain`in favour of `Module.prepend`. I'll send some PRs.

**Comment by GregSutcliffe** [comment]
Thanks @timogoebel - I wasn't sure if the issue was here or in salt, but as monitoring was the common element in both cases I figured I'd start here.

**Comment by timogoebel** [comment]
@GregSutcliffe: I opened PRs against foreman_salt and foreman_cockpit. I don't know if any other plugins are affected, but we should fix this across all plugins.
