### ISSUE TITLE
How do I get the right version for 1.16.0 back again?

### ISSUE THREAD

**Issue by hboetes** [theforeman/foreman_monitoring#35]
I upgraded the plugin to be greeted with this error:

```
Foreman::PluginRequirementError: ERF72-1742 [Foreman::PluginRequirementError]: foreman_monitoring plugin requires Foreman >= 1.17 but current is 1.16.0
```

How do I get the right version installed?

**Comment by timogoebel** [comment]
The 0.1.1 release is the latest for 1.15. Don't use the master branch, it's for 1.17 now.

**Comment by hboetes** [comment]
Well, that's the one I'm using:

Using foreman_monitoring 0.1.1 from https://github.com/theforeman/foreman_monitoring.git (at master@7abaf20)

**Comment by timogoebel** [comment]
release 0.1.1 still supports 1.15, see

https://github.com/theforeman/foreman_monitoring/blob/761ce29755309ae7aac1c66461079df469d66fc0/lib/foreman_monitoring/engine.rb#L32

You do use the master branch, make sure your Gemfile looks something like this:

```
gem 'foreman_monitoring', :git => 'https://github.com/theforeman/foreman_monitoring.git', :tag => '0.1.1'
```

The tag is important, or it will fallback to "master". The version is not bumped yet, so it may look like that is also 0.1.1 - but it isn't.

**Comment by hboetes** [comment]
Right, here we go:
```
# su - foreman -s /bin/zsh
% cat bundler.d/Gemfile.local.rb
gem 'foreman_monitoring', :git => "https://github.com/theforeman/foreman_monitoring.git", :tag => '0.1.1'
% bundle update foreman_monitoring
[SNIP]
%ls -lart /usr/share/foreman/vendor/ruby/2.3.0/bundler/gems/
% ls -lart /usr/share/foreman/vendor/ruby/2.3.0/bundler/gems/|tail -n 1
drwxrwxr-x 10 foreman foreman 4096 Jan  8 08:27 foreman_monitoring-afddf406f92c
% grep '1\.1' /usr/share/foreman/vendor/ruby/2.3.0/bundler/gems/foreman_monitoring-afddf406f92c/lib/foreman_monitoring/engine.rb 
32:        requires_foreman '>= 1.15'
% exit
# foreman-rake apipie:cache
[SNIP]
```
