### ISSUE TITLE
Location attribute is incorrectly set as organization

### ISSUE THREAD

**Issue by vpsman** [theforeman/foreman_monitoring#41]
Hosts added via the Director incorrectly have vars.location set to the organization.

https://github.com/theforeman/foreman_monitoring/blob/979c2a6a54a3b3b213801c596a2e80ed5b4ae0fa/app/models/concerns/foreman_monitoring/host_extensions.rb#L67

**Comment by timogoebel** [comment]
@vpsman: Thanks for the report. #43 should contain a fix for this.
