### ISSUE TITLE
screenshots?

### ISSUE THREAD

**Issue by tek0011** [theforeman/foreman_monitoring#42]
Are there any screenshots of what this looks like in various menus/pages?

**Comment by dgoetz** [comment]
Not yet, but I was already thinking about adding it to https://theforeman.org/plugins/ and include screenshot there.

I found some screenshot I made for a colleague some time ago.
* Global status
![bildschirmfoto von 2016-11-10 21-55-13](https://user-images.githubusercontent.com/3658213/35994422-af2deba8-0d10-11e8-8f0b-f26b6dff0e70.png)
* Monitoring status
![bildschirmfoto von 2016-11-10 21-54-31](https://user-images.githubusercontent.com/3658213/35994423-af5241c4-0d10-11e8-80a1-36c129f5142a.png)

Furthermore you can see how it looks like in the [deep dive](https://www.youtube.com/watch?v=-w9f5xEPki0) where we introduced it.

**Comment by tek0011** [comment]
Wow!  Thanks for the fast turn around.  Neat.  I'll try it out.
