### ISSUE TITLE
Can monitoring proxy not be inherited from Host Groups?

### ISSUE THREAD

**Issue by scroogie** [theforeman/foreman_monitoring#78]
It seems not possible to inherit the monitoring proxy from a Host Group, or am I doing something wrong? While the host group has the proxy set, I still need to set the monitoring proxy on every individual host. Is there a better way to automate that?

**Comment by timogoebel** [comment]
This looks like a bug that we'd need to investigate.

**Comment by scroogie** [comment]
Oh this is true indeed, sorry if it's a wrong report then. We'll try to verify it with new hosts this week!

**Comment by dgoetz** [comment]
@scroogie: Had you any chance to verify this?

**Comment by scroogie** [comment]
Yes, it works for new hosts, sorry for the late answer.
