### ISSUE TITLE
Problem after foreman 3.1 upgrade

### ISSUE THREAD

**Issue by alexdga** [theforeman/foreman_monitoring#80]
Foreman monitoring plugin does not update icinga statuses anymore on hosts, this used to work until version 3.0.1.
Since i’ve upgraded to foreman 3.1, the proxy part still works as expected, but the foreman server logs this :
Started POST “/api/monitoring_results”
ActionController::RoutingError (No route matches [POST] “/api/monitoring_results”)

**Comment by alexdga** [comment]
Any update on this ? Plugin does not work anymore since 4 months now.

**Comment by ekohl** [comment]
https://github.com/theforeman/smart_proxy_monitoring/pull/28 worked for me. I've patched my instance locally and it started sending results again.

**Comment by alexdga** [comment]
Ty ekohl, this is working :)

**Comment by ekohl** [comment]
Closing since the problem was on the Smart Proxy side.
