### ISSUE TITLE
Problem with foreman 3.4 upgrade

### ISSUE THREAD

**Issue by alexdga** [theforeman/foreman_monitoring#82]
Upgrade from foreman 3.3 to foreman 3.4 fails with the following error, like many other plugins.

ActiveModel::UnknownAttributeError: unknown attribute 'description' for Setting::Monitoring.

This is because starting from foreman 3.4, plugins default settings can't be stored in database anymore.

**Comment by janfickler** [comment]
can this PR pushed forward please ? ... foreman 3.4 is not working anymore if the plugin is installed without a fix.
So many users seems to be affected.

see also - https://community.theforeman.org/t/foreman-3-4-stable-unknown-attribute-description-for-setting-foremanhostextravalidator/30333/19

**Comment by alexdga** [comment]
foreman_monitoring is now the only plugin left that breaks my upgrade to foreman 3.4. Any news about this ?

Ty.
